version: 2.0

jobs:
  build:
    docker:
    - image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: secret
    - image: redis:3.2
    steps:
    - checkout
    - restore_cache:
        name: restore composer cache
        key: composer-{{ checksum "composer.lock" }}
    - run:
        name: show php extensions
        command: php -m
    - run:
        name: provision
        command: bash provision.sh --force --env=circleci
    - save_cache:
        name: save composer cache
        key: composer-{{ checksum "composer.lock" }}
        paths:
        - ~/.composer/cache
    - run:
        name: refresh migration
        command: php artisan migrate:refresh
    - run:
        name: show all routes
        command: php artisan route:list || exit 1
