<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: auth/Type.proto

namespace App\Proto\Type {

  class AuthenticateType extends \DrSlump\Protobuf\Enum {
    const Google = 1;
    const Facebook = 2;
    const Guest = 3;
  }
}
