<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: character/Character.proto

namespace App\Proto {

  class Character extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $name = null;
    
    /**  @var int */
    public $hp = null;
    
    /**  @var int */
    public $speed = null;
    
    /**  @var int */
    public $attack = null;
    
    /**  @var string */
    public $resourceID = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.Character');

      // REQUIRED STRING name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 hp = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "hp";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 speed = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "speed";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 attack = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "attack";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED STRING resourceID = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "resourceID";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <name> value
     *
     * @return \App\Proto\Character
     */
    public function clearName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(1);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \App\Proto\Character
     */
    public function setName( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <hp> has a value
     *
     * @return boolean
     */
    public function hasHp(){
      return $this->_has(2);
    }
    
    /**
     * Clear <hp> value
     *
     * @return \App\Proto\Character
     */
    public function clearHp(){
      return $this->_clear(2);
    }
    
    /**
     * Get <hp> value
     *
     * @return int
     */
    public function getHp(){
      return $this->_get(2);
    }
    
    /**
     * Set <hp> value
     *
     * @param int $value
     * @return \App\Proto\Character
     */
    public function setHp( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <speed> has a value
     *
     * @return boolean
     */
    public function hasSpeed(){
      return $this->_has(3);
    }
    
    /**
     * Clear <speed> value
     *
     * @return \App\Proto\Character
     */
    public function clearSpeed(){
      return $this->_clear(3);
    }
    
    /**
     * Get <speed> value
     *
     * @return int
     */
    public function getSpeed(){
      return $this->_get(3);
    }
    
    /**
     * Set <speed> value
     *
     * @param int $value
     * @return \App\Proto\Character
     */
    public function setSpeed( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <attack> has a value
     *
     * @return boolean
     */
    public function hasAttack(){
      return $this->_has(4);
    }
    
    /**
     * Clear <attack> value
     *
     * @return \App\Proto\Character
     */
    public function clearAttack(){
      return $this->_clear(4);
    }
    
    /**
     * Get <attack> value
     *
     * @return int
     */
    public function getAttack(){
      return $this->_get(4);
    }
    
    /**
     * Set <attack> value
     *
     * @param int $value
     * @return \App\Proto\Character
     */
    public function setAttack( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <resourceID> has a value
     *
     * @return boolean
     */
    public function hasResourceID(){
      return $this->_has(5);
    }
    
    /**
     * Clear <resourceID> value
     *
     * @return \App\Proto\Character
     */
    public function clearResourceID(){
      return $this->_clear(5);
    }
    
    /**
     * Get <resourceID> value
     *
     * @return string
     */
    public function getResourceID(){
      return $this->_get(5);
    }
    
    /**
     * Set <resourceID> value
     *
     * @param string $value
     * @return \App\Proto\Character
     */
    public function setResourceID( $value){
      return $this->_set(5, $value);
    }
  }
}

