<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: match/EndMatchParameter.proto

namespace App\Proto {

  class EndMatchParameter extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $dropGold = null;
    
    /**  @var int */
    public $hp = null;
    
    /**  @var int */
    public $waveID = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.EndMatchParameter');

      // REQUIRED UINT32 dropGold = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "dropGold";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 hp = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "hp";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 waveID = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "waveID";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <dropGold> has a value
     *
     * @return boolean
     */
    public function hasDropGold(){
      return $this->_has(1);
    }
    
    /**
     * Clear <dropGold> value
     *
     * @return \App\Proto\EndMatchParameter
     */
    public function clearDropGold(){
      return $this->_clear(1);
    }
    
    /**
     * Get <dropGold> value
     *
     * @return int
     */
    public function getDropGold(){
      return $this->_get(1);
    }
    
    /**
     * Set <dropGold> value
     *
     * @param int $value
     * @return \App\Proto\EndMatchParameter
     */
    public function setDropGold( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <hp> has a value
     *
     * @return boolean
     */
    public function hasHp(){
      return $this->_has(3);
    }
    
    /**
     * Clear <hp> value
     *
     * @return \App\Proto\EndMatchParameter
     */
    public function clearHp(){
      return $this->_clear(3);
    }
    
    /**
     * Get <hp> value
     *
     * @return int
     */
    public function getHp(){
      return $this->_get(3);
    }
    
    /**
     * Set <hp> value
     *
     * @param int $value
     * @return \App\Proto\EndMatchParameter
     */
    public function setHp( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <waveID> has a value
     *
     * @return boolean
     */
    public function hasWaveID(){
      return $this->_has(4);
    }
    
    /**
     * Clear <waveID> value
     *
     * @return \App\Proto\EndMatchParameter
     */
    public function clearWaveID(){
      return $this->_clear(4);
    }
    
    /**
     * Get <waveID> value
     *
     * @return int
     */
    public function getWaveID(){
      return $this->_get(4);
    }
    
    /**
     * Set <waveID> value
     *
     * @param int $value
     * @return \App\Proto\EndMatchParameter
     */
    public function setWaveID( $value){
      return $this->_set(4, $value);
    }
  }
}

