<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: character/HavingCharacter.proto

namespace App\Proto {

  class HavingCharacter extends \DrSlump\Protobuf\Message {

    /**  @var \App\Proto\Character[]  */
    public $character = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.HavingCharacter');

      // REPEATED MESSAGE character = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "character";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\App\Proto\Character';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <character> has a value
     *
     * @return boolean
     */
    public function hasCharacter(){
      return $this->_has(1);
    }
    
    /**
     * Clear <character> value
     *
     * @return \App\Proto\HavingCharacter
     */
    public function clearCharacter(){
      return $this->_clear(1);
    }
    
    /**
     * Get <character> value
     *
     * @param int $idx
     * @return \App\Proto\Character
     */
    public function getCharacter($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <character> value
     *
     * @param \App\Proto\Character $value
     * @return \App\Proto\HavingCharacter
     */
    public function setCharacter(\App\Proto\Character $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <character>
     *
     * @return \App\Proto\Character[]
     */
    public function getCharacterList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <character>
     *
     * @param \App\Proto\Character $value
     * @return \App\Proto\HavingCharacter
     */
    public function addCharacter(\App\Proto\Character $value){
     return $this->_add(1, $value);
    }
  }
}

