<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: ProtobufMessage.proto

namespace App\Proto {

  class ProtobufMessage extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $type = null;
    
    /**  @var string */
    public $payload = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.ProtobufMessage');

      // REQUIRED UINT32 type = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "type";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED BYTES payload = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "payload";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <type> has a value
     *
     * @return boolean
     */
    public function hasType(){
      return $this->_has(1);
    }
    
    /**
     * Clear <type> value
     *
     * @return \App\Proto\ProtobufMessage
     */
    public function clearType(){
      return $this->_clear(1);
    }
    
    /**
     * Get <type> value
     *
     * @return int
     */
    public function getType(){
      return $this->_get(1);
    }
    
    /**
     * Set <type> value
     *
     * @param int $value
     * @return \App\Proto\ProtobufMessage
     */
    public function setType( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <payload> has a value
     *
     * @return boolean
     */
    public function hasPayload(){
      return $this->_has(2);
    }
    
    /**
     * Clear <payload> value
     *
     * @return \App\Proto\ProtobufMessage
     */
    public function clearPayload(){
      return $this->_clear(2);
    }
    
    /**
     * Get <payload> value
     *
     * @return string
     */
    public function getPayload(){
      return $this->_get(2);
    }
    
    /**
     * Set <payload> value
     *
     * @param string $value
     * @return \App\Proto\ProtobufMessage
     */
    public function setPayload( $value){
      return $this->_set(2, $value);
    }
  }
}

