<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: ProtobufMessages.proto

namespace App\Proto {

  class ProtobufMessages extends \DrSlump\Protobuf\Message {

    /**  @var \App\Proto\ProtobufMessage[]  */
    public $messages = array();
    
    /**  @var int */
    public $count = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.ProtobufMessages');

      // REPEATED MESSAGE messages = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "messages";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\App\Proto\ProtobufMessage';
      $descriptor->addField($f);

      // REQUIRED INT32 count = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "count";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <messages> has a value
     *
     * @return boolean
     */
    public function hasMessages(){
      return $this->_has(1);
    }
    
    /**
     * Clear <messages> value
     *
     * @return \App\Proto\ProtobufMessages
     */
    public function clearMessages(){
      return $this->_clear(1);
    }
    
    /**
     * Get <messages> value
     *
     * @param int $idx
     * @return \App\Proto\ProtobufMessage
     */
    public function getMessages($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <messages> value
     *
     * @param \App\Proto\ProtobufMessage $value
     * @return \App\Proto\ProtobufMessages
     */
    public function setMessages(\App\Proto\ProtobufMessage $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <messages>
     *
     * @return \App\Proto\ProtobufMessage[]
     */
    public function getMessagesList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <messages>
     *
     * @param \App\Proto\ProtobufMessage $value
     * @return \App\Proto\ProtobufMessages
     */
    public function addMessages(\App\Proto\ProtobufMessage $value){
     return $this->_add(1, $value);
    }
    
    /**
     * Check if <count> has a value
     *
     * @return boolean
     */
    public function hasCount(){
      return $this->_has(2);
    }
    
    /**
     * Clear <count> value
     *
     * @return \App\Proto\ProtobufMessages
     */
    public function clearCount(){
      return $this->_clear(2);
    }
    
    /**
     * Get <count> value
     *
     * @return int
     */
    public function getCount(){
      return $this->_get(2);
    }
    
    /**
     * Set <count> value
     *
     * @param int $value
     * @return \App\Proto\ProtobufMessages
     */
    public function setCount( $value){
      return $this->_set(2, $value);
    }
  }
}

