<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: auth/Imei.proto

namespace App\Proto {

  class RequestAccessTokenParameter extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $imei = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.RequestAccessTokenParameter');

      // REQUIRED STRING imei = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "imei";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <imei> has a value
     *
     * @return boolean
     */
    public function hasImei(){
      return $this->_has(1);
    }
    
    /**
     * Clear <imei> value
     *
     * @return \App\Proto\RequestAccessTokenParameter
     */
    public function clearImei(){
      return $this->_clear(1);
    }
    
    /**
     * Get <imei> value
     *
     * @return string
     */
    public function getImei(){
      return $this->_get(1);
    }
    
    /**
     * Set <imei> value
     *
     * @param string $value
     * @return \App\Proto\RequestAccessTokenParameter
     */
    public function setImei( $value){
      return $this->_set(1, $value);
    }
  }
}

