<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: user/User.proto

namespace App\Proto {

  class User extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $name = null;
    
    /**  @var string */
    public $imei = null;
    
    /**  @var string */
    public $google_id = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.User');

      // REQUIRED STRING name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // OPTIONAL STRING imei = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "imei";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING google_id = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "google_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <name> value
     *
     * @return \App\Proto\User
     */
    public function clearName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(1);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \App\Proto\User
     */
    public function setName( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <imei> has a value
     *
     * @return boolean
     */
    public function hasImei(){
      return $this->_has(2);
    }
    
    /**
     * Clear <imei> value
     *
     * @return \App\Proto\User
     */
    public function clearImei(){
      return $this->_clear(2);
    }
    
    /**
     * Get <imei> value
     *
     * @return string
     */
    public function getImei(){
      return $this->_get(2);
    }
    
    /**
     * Set <imei> value
     *
     * @param string $value
     * @return \App\Proto\User
     */
    public function setImei( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <google_id> has a value
     *
     * @return boolean
     */
    public function hasGoogleId(){
      return $this->_has(3);
    }
    
    /**
     * Clear <google_id> value
     *
     * @return \App\Proto\User
     */
    public function clearGoogleId(){
      return $this->_clear(3);
    }
    
    /**
     * Get <google_id> value
     *
     * @return string
     */
    public function getGoogleId(){
      return $this->_get(3);
    }
    
    /**
     * Set <google_id> value
     *
     * @param string $value
     * @return \App\Proto\User
     */
    public function setGoogleId( $value){
      return $this->_set(3, $value);
    }
  }
}

