<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: wave/WaveItem.proto

namespace App\Proto {

  class WaveItem extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $itemID = null;
    
    /**  @var int */
    public $count = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.WaveItem');

      // REQUIRED UINT32 itemID = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "itemID";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 count = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "count";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <itemID> has a value
     *
     * @return boolean
     */
    public function hasItemID(){
      return $this->_has(1);
    }
    
    /**
     * Clear <itemID> value
     *
     * @return \App\Proto\WaveItem
     */
    public function clearItemID(){
      return $this->_clear(1);
    }
    
    /**
     * Get <itemID> value
     *
     * @return int
     */
    public function getItemID(){
      return $this->_get(1);
    }
    
    /**
     * Set <itemID> value
     *
     * @param int $value
     * @return \App\Proto\WaveItem
     */
    public function setItemID( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <count> has a value
     *
     * @return boolean
     */
    public function hasCount(){
      return $this->_has(2);
    }
    
    /**
     * Clear <count> value
     *
     * @return \App\Proto\WaveItem
     */
    public function clearCount(){
      return $this->_clear(2);
    }
    
    /**
     * Get <count> value
     *
     * @return int
     */
    public function getCount(){
      return $this->_get(2);
    }
    
    /**
     * Set <count> value
     *
     * @param int $value
     * @return \App\Proto\WaveItem
     */
    public function setCount( $value){
      return $this->_set(2, $value);
    }
  }
}

