<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: wave/WaveZombie.proto

namespace App\Proto {

  class WaveZombie extends \DrSlump\Protobuf\Message {

    /**  @var \App\Proto\Zombie[]  */
    public $zombie = array();
    
    /**  @var int */
    public $quantity = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.WaveZombie');

      // REPEATED MESSAGE zombie = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "zombie";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\App\Proto\Zombie';
      $descriptor->addField($f);

      // REQUIRED UINT32 quantity = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "quantity";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <zombie> has a value
     *
     * @return boolean
     */
    public function hasZombie(){
      return $this->_has(1);
    }
    
    /**
     * Clear <zombie> value
     *
     * @return \App\Proto\WaveZombie
     */
    public function clearZombie(){
      return $this->_clear(1);
    }
    
    /**
     * Get <zombie> value
     *
     * @param int $idx
     * @return \App\Proto\Zombie
     */
    public function getZombie($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <zombie> value
     *
     * @param \App\Proto\Zombie $value
     * @return \App\Proto\WaveZombie
     */
    public function setZombie(\App\Proto\Zombie $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <zombie>
     *
     * @return \App\Proto\Zombie[]
     */
    public function getZombieList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <zombie>
     *
     * @param \App\Proto\Zombie $value
     * @return \App\Proto\WaveZombie
     */
    public function addZombie(\App\Proto\Zombie $value){
     return $this->_add(1, $value);
    }
    
    /**
     * Check if <quantity> has a value
     *
     * @return boolean
     */
    public function hasQuantity(){
      return $this->_has(2);
    }
    
    /**
     * Clear <quantity> value
     *
     * @return \App\Proto\WaveZombie
     */
    public function clearQuantity(){
      return $this->_clear(2);
    }
    
    /**
     * Get <quantity> value
     *
     * @return int
     */
    public function getQuantity(){
      return $this->_get(2);
    }
    
    /**
     * Set <quantity> value
     *
     * @param int $value
     * @return \App\Proto\WaveZombie
     */
    public function setQuantity( $value){
      return $this->_set(2, $value);
    }
  }
}

