<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: wave/Wave.proto

namespace App\Proto {

  class Wave extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $name = null;
    
    /**  @var \App\Proto\WaveZombie[]  */
    public $waveZombies = array();
    
    /**  @var string */
    public $resourceID = null;
    
    /**  @var \App\Proto\ZombiePosition[]  */
    public $zombiePositions = array();
    
    /**  @var \App\Proto\WaveItem[]  */
    public $waveItems = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.Wave');

      // REQUIRED STRING name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REPEATED MESSAGE waveZombies = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "waveZombies";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\App\Proto\WaveZombie';
      $descriptor->addField($f);

      // REQUIRED STRING resourceID = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "resourceID";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REPEATED MESSAGE zombiePositions = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "zombiePositions";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\App\Proto\ZombiePosition';
      $descriptor->addField($f);

      // REPEATED MESSAGE waveItems = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "waveItems";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\App\Proto\WaveItem';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <name> value
     *
     * @return \App\Proto\Wave
     */
    public function clearName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(1);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \App\Proto\Wave
     */
    public function setName( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <waveZombies> has a value
     *
     * @return boolean
     */
    public function hasWaveZombies(){
      return $this->_has(2);
    }
    
    /**
     * Clear <waveZombies> value
     *
     * @return \App\Proto\Wave
     */
    public function clearWaveZombies(){
      return $this->_clear(2);
    }
    
    /**
     * Get <waveZombies> value
     *
     * @param int $idx
     * @return \App\Proto\WaveZombie
     */
    public function getWaveZombies($idx = NULL){
      return $this->_get(2, $idx);
    }
    
    /**
     * Set <waveZombies> value
     *
     * @param \App\Proto\WaveZombie $value
     * @return \App\Proto\Wave
     */
    public function setWaveZombies(\App\Proto\WaveZombie $value, $idx = NULL){
      return $this->_set(2, $value, $idx);
    }
    
    /**
     * Get all elements of <waveZombies>
     *
     * @return \App\Proto\WaveZombie[]
     */
    public function getWaveZombiesList(){
     return $this->_get(2);
    }
    
    /**
     * Add a new element to <waveZombies>
     *
     * @param \App\Proto\WaveZombie $value
     * @return \App\Proto\Wave
     */
    public function addWaveZombies(\App\Proto\WaveZombie $value){
     return $this->_add(2, $value);
    }
    
    /**
     * Check if <resourceID> has a value
     *
     * @return boolean
     */
    public function hasResourceID(){
      return $this->_has(3);
    }
    
    /**
     * Clear <resourceID> value
     *
     * @return \App\Proto\Wave
     */
    public function clearResourceID(){
      return $this->_clear(3);
    }
    
    /**
     * Get <resourceID> value
     *
     * @return string
     */
    public function getResourceID(){
      return $this->_get(3);
    }
    
    /**
     * Set <resourceID> value
     *
     * @param string $value
     * @return \App\Proto\Wave
     */
    public function setResourceID( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <zombiePositions> has a value
     *
     * @return boolean
     */
    public function hasZombiePositions(){
      return $this->_has(4);
    }
    
    /**
     * Clear <zombiePositions> value
     *
     * @return \App\Proto\Wave
     */
    public function clearZombiePositions(){
      return $this->_clear(4);
    }
    
    /**
     * Get <zombiePositions> value
     *
     * @param int $idx
     * @return \App\Proto\ZombiePosition
     */
    public function getZombiePositions($idx = NULL){
      return $this->_get(4, $idx);
    }
    
    /**
     * Set <zombiePositions> value
     *
     * @param \App\Proto\ZombiePosition $value
     * @return \App\Proto\Wave
     */
    public function setZombiePositions(\App\Proto\ZombiePosition $value, $idx = NULL){
      return $this->_set(4, $value, $idx);
    }
    
    /**
     * Get all elements of <zombiePositions>
     *
     * @return \App\Proto\ZombiePosition[]
     */
    public function getZombiePositionsList(){
     return $this->_get(4);
    }
    
    /**
     * Add a new element to <zombiePositions>
     *
     * @param \App\Proto\ZombiePosition $value
     * @return \App\Proto\Wave
     */
    public function addZombiePositions(\App\Proto\ZombiePosition $value){
     return $this->_add(4, $value);
    }
    
    /**
     * Check if <waveItems> has a value
     *
     * @return boolean
     */
    public function hasWaveItems(){
      return $this->_has(5);
    }
    
    /**
     * Clear <waveItems> value
     *
     * @return \App\Proto\Wave
     */
    public function clearWaveItems(){
      return $this->_clear(5);
    }
    
    /**
     * Get <waveItems> value
     *
     * @param int $idx
     * @return \App\Proto\WaveItem
     */
    public function getWaveItems($idx = NULL){
      return $this->_get(5, $idx);
    }
    
    /**
     * Set <waveItems> value
     *
     * @param \App\Proto\WaveItem $value
     * @return \App\Proto\Wave
     */
    public function setWaveItems(\App\Proto\WaveItem $value, $idx = NULL){
      return $this->_set(5, $value, $idx);
    }
    
    /**
     * Get all elements of <waveItems>
     *
     * @return \App\Proto\WaveItem[]
     */
    public function getWaveItemsList(){
     return $this->_get(5);
    }
    
    /**
     * Add a new element to <waveItems>
     *
     * @param \App\Proto\WaveItem $value
     * @return \App\Proto\Wave
     */
    public function addWaveItems(\App\Proto\WaveItem $value){
     return $this->_add(5, $value);
    }
  }
}

