<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: weapon/master/Weapon.proto

namespace App\Proto {

  class Weapon extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $id = null;
    
    /**  @var string */
    public $name = null;
    
    /**  @var \App\Proto\WeaponGroup */
    public $group = null;
    
    /**  @var int */
    public $damage = null;
    
    /**  @var string */
    public $resourceId = null;
    
    /**  @var int */
    public $magCapacity = null;
    
    /**  @var int */
    public $fireSpeed = null;
    
    /**  @var int */
    public $range = null;
    
    /**  @var boolean */
    public $throwable = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.Weapon');

      // REQUIRED UINT32 id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "id";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED STRING name = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED MESSAGE group = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "group";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $f->reference = '\App\Proto\WeaponGroup';
      $descriptor->addField($f);

      // REQUIRED UINT32 damage = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "damage";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED STRING resourceId = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "resourceId";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 magCapacity = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "magCapacity";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 fireSpeed = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "fireSpeed";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 range = 8
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 8;
      $f->name      = "range";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED BOOL throwable = 9
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 9;
      $f->name      = "throwable";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <id> has a value
     *
     * @return boolean
     */
    public function hasId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <id> value
     *
     * @return \App\Proto\Weapon
     */
    public function clearId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <id> value
     *
     * @return int
     */
    public function getId(){
      return $this->_get(1);
    }
    
    /**
     * Set <id> value
     *
     * @param int $value
     * @return \App\Proto\Weapon
     */
    public function setId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(2);
    }
    
    /**
     * Clear <name> value
     *
     * @return \App\Proto\Weapon
     */
    public function clearName(){
      return $this->_clear(2);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(2);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \App\Proto\Weapon
     */
    public function setName( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <group> has a value
     *
     * @return boolean
     */
    public function hasGroup(){
      return $this->_has(3);
    }
    
    /**
     * Clear <group> value
     *
     * @return \App\Proto\Weapon
     */
    public function clearGroup(){
      return $this->_clear(3);
    }
    
    /**
     * Get <group> value
     *
     * @return \App\Proto\WeaponGroup
     */
    public function getGroup(){
      return $this->_get(3);
    }
    
    /**
     * Set <group> value
     *
     * @param \App\Proto\WeaponGroup $value
     * @return \App\Proto\Weapon
     */
    public function setGroup(\App\Proto\WeaponGroup $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <damage> has a value
     *
     * @return boolean
     */
    public function hasDamage(){
      return $this->_has(4);
    }
    
    /**
     * Clear <damage> value
     *
     * @return \App\Proto\Weapon
     */
    public function clearDamage(){
      return $this->_clear(4);
    }
    
    /**
     * Get <damage> value
     *
     * @return int
     */
    public function getDamage(){
      return $this->_get(4);
    }
    
    /**
     * Set <damage> value
     *
     * @param int $value
     * @return \App\Proto\Weapon
     */
    public function setDamage( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <resourceId> has a value
     *
     * @return boolean
     */
    public function hasResourceId(){
      return $this->_has(5);
    }
    
    /**
     * Clear <resourceId> value
     *
     * @return \App\Proto\Weapon
     */
    public function clearResourceId(){
      return $this->_clear(5);
    }
    
    /**
     * Get <resourceId> value
     *
     * @return string
     */
    public function getResourceId(){
      return $this->_get(5);
    }
    
    /**
     * Set <resourceId> value
     *
     * @param string $value
     * @return \App\Proto\Weapon
     */
    public function setResourceId( $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <magCapacity> has a value
     *
     * @return boolean
     */
    public function hasMagCapacity(){
      return $this->_has(6);
    }
    
    /**
     * Clear <magCapacity> value
     *
     * @return \App\Proto\Weapon
     */
    public function clearMagCapacity(){
      return $this->_clear(6);
    }
    
    /**
     * Get <magCapacity> value
     *
     * @return int
     */
    public function getMagCapacity(){
      return $this->_get(6);
    }
    
    /**
     * Set <magCapacity> value
     *
     * @param int $value
     * @return \App\Proto\Weapon
     */
    public function setMagCapacity( $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <fireSpeed> has a value
     *
     * @return boolean
     */
    public function hasFireSpeed(){
      return $this->_has(7);
    }
    
    /**
     * Clear <fireSpeed> value
     *
     * @return \App\Proto\Weapon
     */
    public function clearFireSpeed(){
      return $this->_clear(7);
    }
    
    /**
     * Get <fireSpeed> value
     *
     * @return int
     */
    public function getFireSpeed(){
      return $this->_get(7);
    }
    
    /**
     * Set <fireSpeed> value
     *
     * @param int $value
     * @return \App\Proto\Weapon
     */
    public function setFireSpeed( $value){
      return $this->_set(7, $value);
    }
    
    /**
     * Check if <range> has a value
     *
     * @return boolean
     */
    public function hasRange(){
      return $this->_has(8);
    }
    
    /**
     * Clear <range> value
     *
     * @return \App\Proto\Weapon
     */
    public function clearRange(){
      return $this->_clear(8);
    }
    
    /**
     * Get <range> value
     *
     * @return int
     */
    public function getRange(){
      return $this->_get(8);
    }
    
    /**
     * Set <range> value
     *
     * @param int $value
     * @return \App\Proto\Weapon
     */
    public function setRange( $value){
      return $this->_set(8, $value);
    }
    
    /**
     * Check if <throwable> has a value
     *
     * @return boolean
     */
    public function hasThrowable(){
      return $this->_has(9);
    }
    
    /**
     * Clear <throwable> value
     *
     * @return \App\Proto\Weapon
     */
    public function clearThrowable(){
      return $this->_clear(9);
    }
    
    /**
     * Get <throwable> value
     *
     * @return boolean
     */
    public function getThrowable(){
      return $this->_get(9);
    }
    
    /**
     * Set <throwable> value
     *
     * @param boolean $value
     * @return \App\Proto\Weapon
     */
    public function setThrowable( $value){
      return $this->_set(9, $value);
    }
  }
}

