<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: wave/ZombiePosition.proto

namespace App\Proto {

  class ZombiePosition extends \DrSlump\Protobuf\Message {

    /**  @var \App\Proto\Position[]  */
    public $position = array();
    
    /**  @var int */
    public $time = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.ZombiePosition');

      // REPEATED MESSAGE position = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "position";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\App\Proto\Position';
      $descriptor->addField($f);

      // REQUIRED UINT32 time = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "time";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <position> has a value
     *
     * @return boolean
     */
    public function hasPosition(){
      return $this->_has(1);
    }
    
    /**
     * Clear <position> value
     *
     * @return \App\Proto\ZombiePosition
     */
    public function clearPosition(){
      return $this->_clear(1);
    }
    
    /**
     * Get <position> value
     *
     * @param int $idx
     * @return \App\Proto\Position
     */
    public function getPosition($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <position> value
     *
     * @param \App\Proto\Position $value
     * @return \App\Proto\ZombiePosition
     */
    public function setPosition(\App\Proto\Position $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <position>
     *
     * @return \App\Proto\Position[]
     */
    public function getPositionList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <position>
     *
     * @param \App\Proto\Position $value
     * @return \App\Proto\ZombiePosition
     */
    public function addPosition(\App\Proto\Position $value){
     return $this->_add(1, $value);
    }
    
    /**
     * Check if <time> has a value
     *
     * @return boolean
     */
    public function hasTime(){
      return $this->_has(2);
    }
    
    /**
     * Clear <time> value
     *
     * @return \App\Proto\ZombiePosition
     */
    public function clearTime(){
      return $this->_clear(2);
    }
    
    /**
     * Get <time> value
     *
     * @return int
     */
    public function getTime(){
      return $this->_get(2);
    }
    
    /**
     * Set <time> value
     *
     * @param int $value
     * @return \App\Proto\ZombiePosition
     */
    public function setTime( $value){
      return $this->_set(2, $value);
    }
  }
}

