<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: zombie/master/Zombie.proto

namespace App\Proto {

  class Zombie extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $id = null;
    
    /**  @var string */
    public $name = null;
    
    /**  @var int */
    public $damage = null;
    
    /**  @var int */
    public $hp = null;
    
    /**  @var int */
    public $speed = null;
    
    /**  @var int */
    public $armor = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'App.Proto.Zombie');

      // REQUIRED UINT32 id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "id";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED STRING name = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 damage = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "damage";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 hp = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "hp";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 speed = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "speed";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT32 armor = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "armor";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <id> has a value
     *
     * @return boolean
     */
    public function hasId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <id> value
     *
     * @return \App\Proto\Zombie
     */
    public function clearId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <id> value
     *
     * @return int
     */
    public function getId(){
      return $this->_get(1);
    }
    
    /**
     * Set <id> value
     *
     * @param int $value
     * @return \App\Proto\Zombie
     */
    public function setId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(2);
    }
    
    /**
     * Clear <name> value
     *
     * @return \App\Proto\Zombie
     */
    public function clearName(){
      return $this->_clear(2);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(2);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \App\Proto\Zombie
     */
    public function setName( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <damage> has a value
     *
     * @return boolean
     */
    public function hasDamage(){
      return $this->_has(3);
    }
    
    /**
     * Clear <damage> value
     *
     * @return \App\Proto\Zombie
     */
    public function clearDamage(){
      return $this->_clear(3);
    }
    
    /**
     * Get <damage> value
     *
     * @return int
     */
    public function getDamage(){
      return $this->_get(3);
    }
    
    /**
     * Set <damage> value
     *
     * @param int $value
     * @return \App\Proto\Zombie
     */
    public function setDamage( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <hp> has a value
     *
     * @return boolean
     */
    public function hasHp(){
      return $this->_has(4);
    }
    
    /**
     * Clear <hp> value
     *
     * @return \App\Proto\Zombie
     */
    public function clearHp(){
      return $this->_clear(4);
    }
    
    /**
     * Get <hp> value
     *
     * @return int
     */
    public function getHp(){
      return $this->_get(4);
    }
    
    /**
     * Set <hp> value
     *
     * @param int $value
     * @return \App\Proto\Zombie
     */
    public function setHp( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <speed> has a value
     *
     * @return boolean
     */
    public function hasSpeed(){
      return $this->_has(5);
    }
    
    /**
     * Clear <speed> value
     *
     * @return \App\Proto\Zombie
     */
    public function clearSpeed(){
      return $this->_clear(5);
    }
    
    /**
     * Get <speed> value
     *
     * @return int
     */
    public function getSpeed(){
      return $this->_get(5);
    }
    
    /**
     * Set <speed> value
     *
     * @param int $value
     * @return \App\Proto\Zombie
     */
    public function setSpeed( $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <armor> has a value
     *
     * @return boolean
     */
    public function hasArmor(){
      return $this->_has(6);
    }
    
    /**
     * Clear <armor> value
     *
     * @return \App\Proto\Zombie
     */
    public function clearArmor(){
      return $this->_clear(6);
    }
    
    /**
     * Get <armor> value
     *
     * @return int
     */
    public function getArmor(){
      return $this->_get(6);
    }
    
    /**
     * Set <armor> value
     *
     * @param int $value
     * @return \App\Proto\Zombie
     */
    public function setArmor( $value){
      return $this->_set(6, $value);
    }
  }
}

